version: "3.7"
services:
  front-envoy:
    image: "conservify/proxy-envoy:${TAG}"
    networks:
      - envoy-mesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    image: "conservify/dummy-service:${TAG}"
    networks:
      envoy-mesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service2:
    image: "conservify/dummy-service:${TAG}"
    networks:
      envoy-mesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"

networks:
  envoy-mesh: {}
