version: "3.7"
services:
  front-envoy:
    image: "conservify/envoy-proxy:active"
    networks:
      - envoy-mesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

  service1:
    image: "conservify/dummy-service:active"
    networks:
      envoy-mesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

  service2:
    image: "conservify/dummy-service:active"
    networks:
      envoy-mesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

networks:
  envoy-mesh:
    name: envoy-mesh
