properties([pipelineTriggers([cron('@weekly')])])

timestamps {
    node () {
        stage ('git') {
            checkout([$class: 'GitSCM', branches: [[name: '*/linux']], userRemoteConfigs: [[url: 'https://github.com/jlewallen/arduino-packages.git']]])
        }

        stage ('build') {
            sh """
AP=`pwd`/packages
for IDE in ../arduino-1.*; do
    (cd ${env.CONSERVIFY_ARDUINO_IDE} && ln -sf ../../arduino-packages/packages packages)
done
"""
	      }
    }
}
