#cloud-config
hostname: ${hostname}
fqdn: ${hostname}.${zone_name}
manage_etc_hosts: true
write_files:
  - path: /etc/user_data.env
    content: |
      HOSTNAME=${hostname}
      SERVER_NAME=${hostname}
      ZONE_NAME=${zone_name}
      ENV_TAG=${env_tag}
      GELF_TAGS=${env_tag}
      GELF_URL=${gelf_url}
      STATSD_ADDRESS=${statsd_address}
      DATABASE_URL=${database_url}
      INFLUX_URL=${influx_url}
      INFLUX_DATABASE=${influx_database}
      INFLUX_USER=${influx_user}
      INFLUX_PASSWORD=${influx_password}
      AWS_ACCESS_KEY=${aws_access_key}
      AWS_SECRET_KEY=${aws_secret_key}
      APPLICATION_START=${application_start}
      APPLICATION_STACK=${application_stack}
      STREAMS_BUCKET_NAME=${streams_bucket_name}
      MEDIA_BUCKET_NAME=${media_bucket_name}
      PRODUCTION=${production}
      EMAIL_OVERRIDE=${email_override}
  - path: /etc/default/filebeat
    content: |
      HOSTNAME=${hostname}
      ENV_TAG=${env_tag}
      FIELDKIT_SERVER_NAME=${hostname}
  - path: /etc/default/telegraf
    content: |
      HOSTNAME=${hostname}
      SERVER_NAME=${hostname}
      ENV_TAG=${env_tag}
      INFLUX_URL=${influx_url}
      INFLUX_DATABASE=${influx_database}
      INFLUX_USER=${influx_user}
      INFLUX_PASSWORD=${influx_password}
      AWS_ACCESS_KEY=${aws_access_key}
      AWS_SECRET_KEY=${aws_secret_key}
      STATSD_ADDRESS=${statsd_address}
      PRODUCTION=${production}
      EMAIL_OVERRIDE=${email_override}
runcmd:
  - [ /var/lib/conservify/startup.sh ]
