version: "3.7"
services:
  proxy:
    image: "conservify/proxy-service:active"
    restart: unless-stopped
    networks:
      - envoy-mesh
    expose:
      - "7000"
      - "8000"
      - "9000"
    ports:
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"

networks:
  envoy-mesh:
    name: envoy-mesh
