fields_under_root: true

logging.metrics.enabled: false

logging.json: true

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/syslog

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

fields:
  tag: ${ENV_TAG}

output.logstash:
  hosts: [ "logs.fk.private:5044" ]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
