fields_under_root: true

logging.metrics.enabled: false

logging.json: true

fields:
  tag: ${ENV_TAG}

filebeat.inputs:
- type: filestream
  id: var-log-syslog
  enabled: true
  paths:
    - "/var/log/syslog"
- type: filestream
  id: var-lib-docker
  enabled: true
  parsers:
    - container:
  paths:
    - "/var/lib/docker/containers/*/*.log"
  processors:
    - add_docker_metadata:

output.logstash:
  enabled: true
  hosts: [ "logs.fk.private:${LOGS_PORT}" ]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
