#!/bin/bash

set -xe

certs_dir=`pwd`/ssl/letsencrypt
logs_dir=`pwd`/ssl/logs
hooks_dir=`pwd`/certbot/hooks
work_dir=`pwd`/ssl

mkdir -p $certs_dir $letsencrypt $hooks_dir

export PATH=$hooks_dir:$PATH
export WEB_ROOT_HOST=fkdev

if [ -d $certs_dir/live/fkdev.org ]; then
	echo existing certificates found, rename
	exit 2
fi

certbot certonly -v --config-dir "$certs_dir" --logs-dir "$logs_dir" --work-dir "$work_dir" \
	--manual \
	--manual-auth-hook $hooks_dir/authenticator.sh \
	--manual-cleanup-hook $hooks_dir/cleanup.sh \
	--preferred-challenges=http \
	-d fkdev.org -d www.fkdev.org -d portal.fkdev.org -d api.fkdev.org -d auth.fkdev.org -d floodnet.fkdev.org \
	-m jacob@conservify.org --expand
