#!/bin/bash

set -xe

certs_dir=`pwd`/ssl/letsencrypt
logs_dir=`pwd`/ssl/logs
hooks_dir=`pwd`/certbot/hooks
work_dir=`pwd`/ssl

mkdir -p $certs_dir $letsencrypt $hooks_dir

make prod env

export WEB_ROOT_HOSTS=`cat build/deploy.json | jq -r '[.app_servers.value[].ip] | join(" ")'`

if [ -d $certs_dir/live/fieldkit.org ]; then
	echo existing certificates found, rename
	exit 2
fi

export PATH=$hooks_dir:$PATH

certbot certonly -v --config-dir "$certs_dir" --logs-dir "$logs_dir" --work-dir "$work_dir" \
	--manual \
	--manual-auth-hook $hooks_dir/authenticator.sh \
	--manual-cleanup-hook $hooks_dir/cleanup.sh \
	--preferred-challenges=http \
	-d portal.fieldkit.org -d api.fieldkit.org -d auth.fieldkit.org -d floodnet.fieldkit.org \
	-d dataviz.floodnet.nyc \
	-m jacob@conservify.org --expand
