#!/bin/bash

set -xe

certs_dir=`pwd`/ssl/letsencrypt
logs_dir=`pwd`/ssl/logs
hooks_dir=`pwd`/certbot/hooks
work_dir=`pwd`/ssl

mkdir -p $certs_dir $letsencrypt $hooks_dir

export PATH=$hooks_dir:$PATH
export WEB_ROOT_HOST=fkprod

if [ -d $certs_dir/live/fieldkit.org ]; then
	echo existing certificates found, rename
	exit 2
fi

certbot certonly -v --config-dir "$certs_dir" --logs-dir "$logs_dir" --work-dir "$work_dir" \
	--manual \
	--manual-auth-hook $hooks_dir/authenticator.sh \
	--manual-cleanup-hook $hooks_dir/cleanup.sh \
	--preferred-challenges=http \
	-d fieldkit.org -d www.fieldkit.org -d portal.fieldkit.org -d api.fieldkit.org -d auth.fieldkit.org -d floodnet.fieldkit.org \
	-d dataviz.floodnet.nyc \
	-m jacob@conservify.org --expand
