properties([
    [$class: 'BuildDiscarderProperty', strategy: [$class: 'LogRotator', numToKeepStr: '5']],
    pipelineTriggers([[$class: 'GitHubPushTrigger']]),
    disableConcurrentBuilds(),
])

timestamps {
    node () {
        stage ('git') {
            checkout scm
        }

        stage ('build') {
            sh """
make clean build

cp artifacts/*.template /var/lib/distribution
cp artifacts/favicon.png /var/lib/distribution
cp build/artifacts-publisher /var/lib/distribution

ls -alh /var/lib/distribution

cd /var/lib/distribution

./artifacts-publisher --source ~/jobs --destination /var/lib/distribution
"""
        }
    }
}
