version: "3.7"
services:
  fk-charting:
    image: "conservify/charting-service:active"
    networks:
      - envoy-mesh
    environment:
      - TAG=${TAG}
      - HOSTNAME=${HOSTNAME}
      - FIELDKIT_TAG=${TAG}
      - FIELDKIT_SERVER_NAME=${HOSTNAME}
      - FIELDKIT_DOMAIN=${ZONE_NAME}
      - FIELDKIT_PRODUCTION=${PRODUCTION}
      - FIELDKIT_LOGGING_FULL=true
      - FIELDKIT_STATSD_ADDRESS=172.17.0.1:8125
      - FIELDKIT_PORT=8000
      - FIELDKIT_BASE_URL=http://fk-service:8000
    expose:
      - "8000"

networks:
  envoy-mesh:
    name: envoy-mesh
