version: "3.7"
services:
  proxy:
    image: "conservify/fk-cloud-proxy:active"
    networks:
      - envoy-mesh
    expose:
      - "7000"
      - "8000"
      - "9000"
    ports:
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

  fk-ingester:
    image: "conservify/fk-cloud-service:active"
    command: [ "/app/ingester" ]
    networks:
      - envoy-mesh
    environment:
      - TAG=${TAG}
      - HOSTNAME=${HOSTNAME}
      - FIELDKIT_TAG=${TAG}
      - FIELDKIT_SERVER_NAME=${HOSTNAME}
      - FIELDKIT_POSTGRES_URL=${DATABASE_URL}
      - FIELDKIT_DOMAIN=${ZONE_NAME}
      - FIELDKIT_PORTAL_ROOT=/app/portal
      - FIELDKIT_LEGACY_ROOT=/app/legacy
      - FIELDKIT_EMAILER=aws
      - FIELDKIT_ARCHIVER=aws
      - FIELDKIT_EMAIL_OVERRIDE=${EMAIL_OVERRIDE}
      - FIELDKIT_PRODUCTION=${PRODUCTION}
      - FIELDKIT_LOGGING_FULL=true
      - FIELDKIT_STATSD_ADDRESS=172.17.0.1:8125
      - FIELDKIT_MEDIA_BUCKET_NAME=${MEDIA_BUCKET_NAME}
      - FIELDKIT_STREAMS_BUCKET_NAME=${STREAMS_BUCKET_NAME}
      - FIELDKIT_SESSION_KEY=${SESSION_KEY}
    expose:
      - "8000"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

  fk-service:
    image: "conservify/fk-cloud-service:active"
    command: [ "/app/server" ]
    networks:
      - envoy-mesh
    environment:
      - TAG=${TAG}
      - HOSTNAME=${HOSTNAME}
      - FIELDKIT_TAG=${TAG}
      - FIELDKIT_SERVER_NAME=${HOSTNAME}
      - FIELDKIT_POSTGRES_URL=${DATABASE_URL}
      - FIELDKIT_DOMAIN=${ZONE_NAME}
      - FIELDKIT_PORTAL_ROOT=/app/portal
      - FIELDKIT_LEGACY_ROOT=/app/legacy
      - FIELDKIT_EMAILER=aws
      - FIELDKIT_ARCHIVER=aws
      - FIELDKIT_EMAIL_OVERRIDE=${EMAIL_OVERRIDE}
      - FIELDKIT_PRODUCTION=${PRODUCTION}
      - FIELDKIT_LOGGING_FULL=true
      - FIELDKIT_STATSD_ADDRESS=172.17.0.1:8125
      - FIELDKIT_MEDIA_BUCKET_NAME=${MEDIA_BUCKET_NAME}
      - FIELDKIT_STREAMS_BUCKET_NAME=${STREAMS_BUCKET_NAME}
      - FIELDKIT_SESSION_KEY=${SESSION_KEY}
      - FIELDKIT_MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - FIELDKIT_SAML_CERT=${FIELDKIT_SAML_CERT}
      - FIELDKIT_SAML_KEY=${FIELDKIT_SAML_KEY}
      - FIELDKIT_SAML_SP_URL=${FIELDKIT_SAML_SP_URL}
      - FIELDKIT_SAML_LOGIN_URL=${FIELDKIT_SAML_LOGIN_URL}
      - FIELDKIT_SAML_IPD_META=${FIELDKIT_SAML_IPD_META}
      - FIELDKIT_KEYCLOAK_URL=${FIELDKIT_KEYCLOAK_URL_PRIVATE}
      - FIELDKIT_KEYCLOAK_REALM=${FIELDKIT_KEYCLOAK_REALM}
      - FIELDKIT_KEYCLOAK_API_USER=${FIELDKIT_KEYCLOAK_API_USER}
      - FIELDKIT_KEYCLOAK_API_PASSWORD=${FIELDKIT_KEYCLOAK_API_PASSWORD}
      - FIELDKIT_KEYCLOAK_API_REALM=${FIELDKIT_KEYCLOAK_API_REALM}
      - FIELDKIT_DISCOURSE_SECRET=${FIELDKIT_DISCOURSE_SECRET}
      - FIELDKIT_DISCOURSE_REDIRECT_URL=${FIELDKIT_DISCOURSE_REDIRECT_URL}
      - FIELDKIT_DISCOURSE_ADMIN_KEY=${FIELDKIT_DISCOURSE_ADMIN_KEY}
      - FIELDKIT_OIDC_CLIENT_ID=${FIELDKIT_OIDC_CLIENT_ID}
      - FIELDKIT_OIDC_CLIENT_SECRET=${FIELDKIT_OIDC_CLIENT_SECRET}
      - FIELDKIT_OIDC_REDIRECT_URL=${FIELDKIT_OIDC_REDIRECT_URL}
      - FIELDKIT_OIDC_CONFIG_URL=${FIELDKIT_OIDC_CONFIG_URL}

    expose:
      - "8000"
    volumes:
      - /etc/fk:/etc/fk
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

networks:
  envoy-mesh:
    name: envoy-mesh
