version: "3.7"
services:
  front-envoy:
    image: "conservify/fk-cloud-proxy:${TAG}"
    networks:
      - envoy-mesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

  fk-cloud-service:
    image: "conservify/fk-cloud-service:${TAG}"
    networks:
      - envoy-mesh
    expose:
      - "80"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

networks:
  envoy-mesh: {}
