version: "3.7"
services:
  front-envoy:
    image: "conservify/fk-cloud-proxy:${TAG}"
    networks:
      - envoy-mesh
    expose:
      - "7000"
      - "8000"
      - "9000"
    ports:
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

  fk-cloud-service:
    image: "conservify/fk-cloud-service:${TAG}"
    networks:
      - envoy-mesh
    environment:
      - FIELDKIT_POSTGRES_URL=${DATABASE_URL}
      - FIELDKIT_DOMAIN=${ZONE_NAME}
      - FIELDKIT_PORTAL_ROOT=/app/portal
      - FIELDKIT_LEGACY_ROOT=/app/legacy
      - FIELDKIT_EMAILER=aws
      - FIELDKIT_ARCHIVER=aws
      - FIELDKIT_PRODUCTION_LOGGING=true
    expose:
      - "80"
    logging:
      driver: "gelf"
      options:
        gelf-address: "${GELF_URL}"
        tag: "${GELF_TAGS}"

networks:
  envoy-mesh: {}
