version: '2'
services:
  nexus:
    image: "sonatype/nexus"
    volumes:
      - /svr0/nexus/sonatype-work:/sonatype-work
    ports:
      - "8081:8081"
  fk-landing:
    depends_on:
      - logs
    image: "fk-landing"
  jenkins:
    image: "conservify/jenkins"
    depends_on:
      - logs
    environment:
      JAVA_OPTS: -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/Los_Angeles
      JENKINS_OPTS: --prefix=/jenkins
    volumes:
      - /svr0/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "45900:45900"
      - "49001:8080"
      - "50000:50000"
  jira:
    image: "ivantichy/jira:7.1.7"
    depends_on:
      - logs
    ports:
      - "8080:8080"
    volumes:
      - /svr0/jira/pg:/var/lib/postgresql/9.4/main
      - /svr0/jira/app:/var/atlassian/jira-app
      - /svr0/jira/home:/var/atlassian/jira-home
  proxy:
    image: "nginx-rproxy"
    volumes:
      - /home/jenkins/artifacts:/var/lib/jenkins_artifacts
    links:
      - jenkins
      - nexus
      - fk-landing
      - logs
      - glacier-status
      - jira
    extra_hosts:
      - "parent:127.0.0.1"
    ports:
      - "443:443"
      - "80:80"
  logs-mongo:
    image: "mongo:3"
    volumes:
      - /svr0/graylog/mongo:/data/db
  logs-elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /svr0/graylog/data/elasticsearch:/usr/share/elasticsearch/data
  logs:
    image: graylog2/server:2.1.1-1
    volumes:
      - /svr0/graylog/journal:/usr/share/graylog/data/journal
      - /svr0/graylog/config:/usr/share/graylog/data/config
    env_file:
      - logs.env
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: https://code.conservify.org/logs/api
    links:
      - logs-mongo:mongo
      - logs-elasticsearch:elasticsearch
    ports:
      - "5140:5140"
      - "9000:9000"
      - "12201:12201"
      - "12201/udp:12201/udp"
      - "1514/udp:1514/udp"
  glacier-status:
    image: conservify/glacier-status
    depends_on:
      - logs
    volumes:
      - /var/log:/var/log
    ports:
      - "8000:8000"
volumes:
  jenkins_home:
