version: "3.7"
services:
  proxy:
    image: "conservify/influxdb-service:active"
    restart: unless-stopped
    networks:
      - envoy-mesh
    volumes:
      - /svr0/influxdb/data:/var/lib/influxdb2
      - /svr0/influxdb/config:/etc/influxdb2
    environment:
      - TAG=${TAG}
      - HOSTNAME=${HOSTNAME}
      - FIELDKIT_TAG=${TAG}
      - FIELDKIT_SERVER_NAME=${HOSTNAME}
      - FIELDKIT_DOMAIN=${ZONE_NAME}
      - FIELDKIT_PRODUCTION=${PRODUCTION}
      - FIELDKIT_LOGGING_FULL=true
      - FIELDKIT_STATSD_ADDRESS=172.17.0.1:8125
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${FIELDKIT_INFLUX_DB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${FIELDKIT_INFLUX_DB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${FIELDKIT_INFLUX_DB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${FIELDKIT_INFLUX_DB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${FIELDKIT_INFLUX_DB_TOKEN}
    expose:
      - "8086"
    ports:
      - "8086:8086"

networks:
  envoy-mesh:
    name: envoy-mesh
