#!/bin/bash

mkdir -p /var/log/letsencrypt
rm -f /var/log/letsencrypt/letsencrypt.log

DOMAINS="-d fkdev.org -d api.fkdev.org -d www.fkdev.org"

docker run -it \
           --rm \
           --net host \
           -v /etc/letsencrypt:/etc/letsencrypt \
           -v /var/lib/letsencrypt:/var/lib/letsencrypt \
           -v /var/log/letsencrypt:/var/log/letsencrypt \
           gzm55/certbot certonly --standalone --text $DOMAINS "$@"

cat /var/log/letsencrypt/letsencrypt.log
