#!/bin/bash

docker run -it --rm --net host \
	--env-file aws.env \
	-v /etc/letsencrypt:/etc/letsencrypt \
	-v /var/lib/letsencrypt:/var/lib/letsencrypt \
	certbot/dns-route53 certonly --dns-route53 -d fkdev.org -d www.fkdev.org -d portal.fkdev.org -d api.fkdev.org "$@"

sudo mv letsencrypt letsencrypt-`date +"%Y-%m-%d_%H-%M-%S"`
sudo cp -ar /etc/letsencrypt letsencrypt

echo upload new certificates to aws certificate manager
