#!/bin/bash

sudo whoami

docker run -it \
           --rm \
           --net host \
           -v /etc/letsencrypt:/etc/letsencrypt \
           -v /var/lib/letsencrypt:/var/lib/letsencrypt \
	   -v /svr0/web:/var/www \
           gzm55/certbot certonly --renew-by-default --webroot --preferred-challenges=http -w /var/www/conservify.org -d code.conservify.org -d jitsi.conservify.org -d strapi.conservify.org "$@"

sudo mv letsencrypt letsencrypt-`date +"%Y-%m-%d_%H-%M-%S"`
sudo cp -ar /etc/letsencrypt letsencrypt

echo build a new image to use the new certificate.
