version: "3.7"
services:
  maintenance:
    image: "conservify/maintenance-service:active"
    restart: unless-stopped
    networks:
      - envoy-mesh
    environment:
      - TAG=${TAG}
      - HOSTNAME=${HOSTNAME}
      - FIELDKIT_TAG=${TAG}
      - FIELDKIT_SERVER_NAME=${HOSTNAME}
    expose:
      - "7000"
      - "8000"
      - "9000"
    ports:
      - "7000:7000"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /tmp/scratch:/tmp/scratch

networks:
  envoy-mesh:
    name: envoy-mesh
