version: "3.7"
services:
  fk-ingester:
    image: "conservify/portal-service:active"
    command: [ "/app/ingester" ]
    networks:
      - envoy-mesh
    environment:
      - TAG=${TAG}
      - HOSTNAME=${HOSTNAME}
      - FIELDKIT_TAG=${TAG}
      - FIELDKIT_SERVER_NAME=${HOSTNAME}
      - FIELDKIT_POSTGRES_URL=${DATABASE_URL}
      - FIELDKIT_INFLUX_DB_URL=${FIELDKIT_INFLUX_DB_URL}
      - FIELDKIT_INFLUX_DB_USERNAME=${FIELDKIT_INFLUX_DB_USERNAME}
      - FIELDKIT_INFLUX_DB_PASSWORD=${FIELDKIT_INFLUX_DB_PASSWORD}
      - FIELDKIT_INFLUX_DB_ORG=${FIELDKIT_INFLUX_DB_ORG}
      - FIELDKIT_INFLUX_DB_BUCKET=${FIELDKIT_INFLUX_DB_BUCKET}
      - FIELDKIT_INFLUX_DB_TOKEN=${FIELDKIT_INFLUX_DB_TOKEN}
      - FIELDKIT_DOMAIN=${ZONE_NAME}
      - FIELDKIT_EMAILER=aws
      - FIELDKIT_ARCHIVER=aws
      - FIELDKIT_EMAIL_OVERRIDE=${EMAIL_OVERRIDE}
      - FIELDKIT_PRODUCTION=${PRODUCTION}
      - FIELDKIT_LOGGING_FULL=true
      - FIELDKIT_STATSD_ADDRESS=172.17.0.1:8125
      - FIELDKIT_STREAMS_BUCKET_NAME=${STREAMS_BUCKET_NAME}
      - FIELDKIT_STREAMS_BUCKETS=${STREAMS_BUCKETS}
      - FIELDKIT_SESSION_KEY=${SESSION_KEY}
    expose:
      - "8000"

  fk-service:
    image: "conservify/portal-service:active"
    command: [ "/app/server" ]
    networks:
      - envoy-mesh
    environment:
      - TAG=${TAG}
      - HOSTNAME=${HOSTNAME}
      - FIELDKIT_TAG=${TAG}
      - FIELDKIT_SERVER_NAME=${HOSTNAME}
      - FIELDKIT_POSTGRES_URL=${DATABASE_URL}
      - FIELDKIT_INFLUX_DB_URL=${FIELDKIT_INFLUX_DB_URL}
      - FIELDKIT_INFLUX_DB_USERNAME=${FIELDKIT_INFLUX_DB_USERNAME}
      - FIELDKIT_INFLUX_DB_PASSWORD=${FIELDKIT_INFLUX_DB_PASSWORD}
      - FIELDKIT_INFLUX_DB_ORG=${FIELDKIT_INFLUX_DB_ORG}
      - FIELDKIT_INFLUX_DB_BUCKET=${FIELDKIT_INFLUX_DB_BUCKET}
      - FIELDKIT_INFLUX_DB_TOKEN=${FIELDKIT_INFLUX_DB_TOKEN}
      - FIELDKIT_WORKERS=${FIELDKIT_WORKERS}
      - FIELDKIT_LIVE=${FIELDKIT_LIVE}
      - FIELDKIT_DOMAIN=${ZONE_NAME}
      - FIELDKIT_PORTAL_ROOT=/app/portal
      - FIELDKIT_WELL_KNOWN_ROOT=/app/.well-known
      - FIELDKIT_EMAILER=aws
      - FIELDKIT_ARCHIVER=aws
      - FIELDKIT_EMAIL_OVERRIDE=${EMAIL_OVERRIDE}
      - FIELDKIT_PRODUCTION=${PRODUCTION}
      - FIELDKIT_LOGGING_FULL=true
      - FIELDKIT_STATSD_ADDRESS=172.17.0.1:8125
      - FIELDKIT_MEDIA_BUCKET_NAME=${MEDIA_BUCKET_NAME}
      - FIELDKIT_STREAMS_BUCKET_NAME=${STREAMS_BUCKET_NAME}
      - FIELDKIT_MEDIA_BUCKETS=${MEDIA_BUCKETS}
      - FIELDKIT_STREAMS_BUCKETS=${STREAMS_BUCKETS}
      - FIELDKIT_SESSION_KEY=${SESSION_KEY}
      - FIELDKIT_MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - FIELDKIT_SAML_CERT=${FIELDKIT_SAML_CERT}
      - FIELDKIT_SAML_KEY=${FIELDKIT_SAML_KEY}
      - FIELDKIT_SAML_SP_URL=${FIELDKIT_SAML_SP_URL}
      - FIELDKIT_SAML_LOGIN_URL=${FIELDKIT_SAML_LOGIN_URL}
      - FIELDKIT_SAML_IPD_META=${FIELDKIT_SAML_IPD_META}
      - FIELDKIT_KEYCLOAK_URL=${FIELDKIT_KEYCLOAK_URL_PRIVATE}
      - FIELDKIT_KEYCLOAK_REALM=${FIELDKIT_KEYCLOAK_REALM}
      - FIELDKIT_KEYCLOAK_API_USER=${FIELDKIT_KEYCLOAK_API_USER}
      - FIELDKIT_KEYCLOAK_API_PASSWORD=${FIELDKIT_KEYCLOAK_API_PASSWORD}
      - FIELDKIT_KEYCLOAK_API_REALM=${FIELDKIT_KEYCLOAK_API_REALM}
      - FIELDKIT_DISCOURSE_SECRET=${FIELDKIT_DISCOURSE_SECRET}
      - FIELDKIT_DISCOURSE_REDIRECT_URL=${FIELDKIT_DISCOURSE_REDIRECT_URL}
      - FIELDKIT_DISCOURSE_ADMIN_KEY=${FIELDKIT_DISCOURSE_ADMIN_KEY}
      - FIELDKIT_OIDC_CLIENT_ID=${FIELDKIT_OIDC_CLIENT_ID}
      - FIELDKIT_OIDC_CLIENT_SECRET=${FIELDKIT_OIDC_CLIENT_SECRET}
      - FIELDKIT_OIDC_REDIRECT_URL=${FIELDKIT_OIDC_REDIRECT_URL}
      - FIELDKIT_OIDC_CONFIG_URL=${FIELDKIT_OIDC_CONFIG_URL}
    expose:
      - "8000"
    volumes:
      - /etc/fk:/etc/fk
      - /app/.well-known:/app/.well-known

networks:
  envoy-mesh:
    name: envoy-mesh
