properties([pipelineTriggers([cron('@weekly')])])

timestamps {
    node () {
        stage ('build') {
            sh """
if [ ! -d arduino-1.8.3 ]; then
  if [ ! -f arduino-1.8.3-linux64.tar.xz ]; then
    wget https://downloads.arduino.cc/arduino-1.8.3-linux64.tar.xz
  fi
  tar xf arduino-1.8.3-linux64.tar.xz
fi
env
"""
	      }
    }
}
